#common: &common
#  adapter: postgresql
#  host: localhost
#  encoding: unicode
#  pool: 5
#  username: main
#  password: r00t
#
#development:
#  <<: *common
#  database: TheSmallCode_development
#
#test:
#  <<: *common
#  database: TheSmallCode_test
#
#production:
#  <<: *common
#  database: TheSmallCode_production
